apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema
  namespace: spark-operator
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mysql
              topologyKey: kubernetes.io/hostname
      containers:
        - name: hivemeta
          image: mykidong/hivemetastore:v3.0.0
          command: ["/opt/hive-metastore/bin/schematool"]
          args: ["--verbose" ,"-initSchema" , "-dbType", "mysql" , "-userName", "root",
                 "-passWord", "kakkEKJkj2390dakdjkje1" , "-url", "jdbc:mysql://mysql-service.spark-operator.svc.cluster.local:3306/metastore_db?createDatabaseIfNotExist=true&connectTimeout=1000"]
      restartPolicy: Never
  backoffLimit: 4