apiVersion: v1
kind: Service
metadata:
  name: metastore
  namespace: spark-operator
spec:
  ports:
  - port: 9083
  selector:
    app: metastore
---
apiVersion: v1
kind: Pod
metadata:
  name: metastore
  namespace: spark-operator
  labels:
    app: metastore
spec:
  containers:
  - name: metastore
    image: mykidong/hivemetastore:v3.0.0
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: my-s3-keys
          key: access-key
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: my-s3-keys
          key: secret-key
    ports:
    - containerPort: 9083
    volumeMounts:
    - name: metastore-cfg-vol
      mountPath: /opt/hive-metastore/conf/metastore-site.xml
      subPath: metastore-site.xml
    - name: metastore-cfg-vol
      mountPath: /opt/hadoop/etc/hadoop/core-site.xml
      subPath: core-site.xml
    - name: metastore-cfg-vol
      mountPath: /opt/hive-metastore/conf/metastore-log4j2.properties
      subPath: metastore-log4j2.properties
    command: ["/opt/hive-metastore/bin/start-metastore"]
    args: ["-p", "9083"]
    resources:
      requests:
        memory: 1Gi
        cpu: 200m
    imagePullPolicy: Always
  volumes:
    - name: metastore-cfg-vol
      configMap:
        name: metastore-cfg
